### ISSUE TITLE
SelectBox set selected item

### ISSUE THREAD

**Issue by Barjoke** [MightyMedia/Mighty-Form-Styler#14]
We are able to make everything else work , but we cannot find a way to set the selected item. Both of the following do nothing:

$("#NamedID").val("2");

document.getElementById("NamedID").selectedIndex = 2; 

We have surrounded the select with form and div, but cannot find a reference that makes it work that way either.

**Comment by basvandenwijngaard** [comment]
Sorry for my late reply.

If you set the value of the select element after it is styled with mfs you need te refresh mfs to reflect your changes to the select element. You can do this with the refresh option.

```
$('form').mfs('refresh');
```
This wil updated the html generated by mfs.

Replace `form` with the selector you used to initialize mfs.

I hop this helps. Feel free to ask another question if you run into any problems related to my plugin.
