### ISSUE TITLE
Select an option and my cursor moves back to the top page

### ISSUE THREAD

**Issue by meiloo** [MightyMedia/Mighty-Form-Styler#15]
Hello,

I'd love to use your script. It looks really nice. I've set it up like you showed. It looks good and works except that when I choose an option, I am moved back to the top of my page. I am using it primarily on mobile, so it's really annoying to have to get back down... 
Any idea how I can fix that?

Thanks,
M.

**Comment by basvandenwijngaard** [comment]
Never had this issue before. Are still having this problem? Because then than I have to look in to it.

On mobile/touch devices it usually works better when you use the native select dropdown. Which can be enabled with the disableTouch option.

`$('form').mfs({
    'disableTouch' : true
});`

**Comment by basvandenwijngaard** [comment]
Closing this issue because not being able to reproduce and it's old as hell.
