### ISSUE TITLE
Plugin is already initialized for this object.

### ISSUE THREAD

**Issue by sdrew** [MightyMedia/Mighty-Form-Styler#20]
Calling `$('#myForm').mfs('refresh')` after updating its contents or selection causes an error to be thrown here:

`$.error('Plugin is already initialized for this object.');` [jquery.mfs.js#L819](https://github.com/MightyMedia/Mighty-Form-Styler/blob/master/jquery.mfs.js#L819)

Fortunately, it does work, but throws the error nonetheless.

**Comment by basvandenwijngaard** [comment]
Hi Stephen,

I cannot seem to reproduce this issue (although, I did found an other issue while trying to debug).

Can you provide me with more details about this case (used versions of jquery and mfs) and maybe even an working example?

Thanks!
